import { test, after } from "node:test";
import assert from "node:assert/strict";
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";
import { defaultConfig } from "../src/config.mjs";
import {
  generatedFiles,
  renderAgentsBlock,
  renderGeneratedFile,
  mergeSettings,
  mergeCodexHooks,
  hookWiredIn,
  codexHookWiredIn,
  wireHooks,
  orphanedHarnessArtifacts,
} from "../src/generate.mjs";
import { tmpRepo, cleanupAll, ROOT } from "./helpers.mjs";

after(cleanupAll);

const cfg = (over = {}) =>
  defaultConfig({
    project: "demo",
    language: "en",
    harnesses: ["claude", "codex"],
    linearTeam: "Demo",
    issuePrefix: "DEM",
    defaultProject: "",
    baseBranch: "main",
    buildGates: "npm test",
    autoMerge: true,
    highRisk: [],
    singleWriter: [],
    ...over,
  });

const targets = (harnesses) => generatedFiles(harnesses).map((s) => s.target);

test("generatedFiles filters by active harness", () => {
  assert.deepEqual(targets(["claude"]), [
    ".claude/commands/create-issue.md",
    ".claude/commands/start-task.md",
    ".claude/hooks/branch-guard.mjs",
  ]);
  assert.deepEqual(targets(["codex"]), [
    ".agents/skills/create-issue/SKILL.md",
    ".agents/skills/start-task/SKILL.md",
    ".codex/hooks/branch-guard.mjs",
  ]);
  assert.equal(targets(["claude", "codex"]).length, 6);
  assert.deepEqual(targets([]), []);
  assert.deepEqual(targets(undefined), []);
});

test("both harnesses share the same branch-guard template", () => {
  const specs = generatedFiles(["claude", "codex"]);
  const guards = specs.filter((s) => s.kind === "mjs");
  assert.equal(guards.length, 2);
  assert.equal(new Set(guards.map((s) => s.template)).size, 1, "one shared template");
});

test("renderAgentsBlock resolves all tokens and labels harnesses", () => {
  const out = renderAgentsBlock(cfg());
  assert.match(out, /Harnesses:\*\* Claude Code \+ Codex/);
  assert.doesNotMatch(out, /\{\{[a-zA-Z]+\}\}/, "no unresolved tokens");
  // Review paragraph is harness-neutral (no subagent_type leak).
  assert.doesNotMatch(out, /subagent_type=/);
  assert.match(out, /codex exec/);
});

test("renderAgentsBlock renders reviewer stances in the review paragraph", () => {
  const out = renderAgentsBlock(cfg());
  assert.match(out, /distinct stance/);
  assert.match(out, /adversarial, spec-conformance, maintainer/);
  assert.match(out, /round-robin/);
});

test("renderAgentsBlock reflects custom stances from config", () => {
  const c = cfg();
  c.review.stances = ["security", "performance"];
  assert.match(renderAgentsBlock(c), /security, performance/);
});

test("committed start-task templates instruct per-reviewer stances", () => {
  for (const rel of [
    "templates/claude/commands/start-task.md",
    "templates/codex/skills/start-task/SKILL.md",
  ]) {
    const body = readFileSync(join(ROOT, rel), "utf8");
    assert.match(body, /stance/i, `${rel} should reference reviewer stances`);
    assert.match(body, /config\.review\.stances/, `${rel} should read config.review.stances`);
    assert.match(body, /round-robin/, `${rel} should describe round-robin assignment`);
    assert.match(body, /spec-conformance/, `${rel} should name the spec-conformance stance`);
  }
});

test("renderAgentsBlock label for a single harness", () => {
  assert.match(renderAgentsBlock(cfg({ harnesses: ["codex"] })), /Harnesses:\*\* Codex\./);
  assert.match(renderAgentsBlock(cfg({ harnesses: ["claude"] })), /Harnesses:\*\* Claude Code\./);
});

test("renderAgentsBlock reflects merge.auto policy", () => {
  assert.match(renderAgentsBlock(cfg({ autoMerge: true })), /Auto-merge \(on/);
  assert.match(renderAgentsBlock(cfg({ autoMerge: false })), /Auto-merge \(off/);
});

test("renderGeneratedFile inserts the DO-NOT-EDIT header after the shebang", () => {
  const rendered = renderGeneratedFile("hooks/branch-guard.mjs", "mjs");
  const lines = rendered.split("\n");
  assert.match(lines[0], /^#!/);
  assert.match(lines[1], /GENERATED by dienstweg/);
});

test("renderGeneratedFile inserts the header after markdown frontmatter", () => {
  const rendered = renderGeneratedFile("codex/skills/create-issue/SKILL.md", "md");
  assert.ok(rendered.startsWith("---\nname: create-issue"), "frontmatter stays first");
  const fmEnd = rendered.indexOf("\n---\n");
  const headerIdx = rendered.indexOf("<!-- GENERATED by dienstweg");
  assert.ok(fmEnd !== -1 && headerIdx > fmEnd, "header comes after the frontmatter block");
});

test("mergeSettings wires the Claude hook, is idempotent, and survives malformed JSON", () => {
  const root = tmpRepo();
  const a1 = mergeSettings(root);
  assert.equal(a1.wired, true);
  assert.equal(hookWiredIn(root), "settings.json");
  // idempotent: a second merge does not duplicate
  const a2 = mergeSettings(root);
  assert.equal(a2.wired, true);
  const pre = JSON.parse(readFileSync(join(root, ".claude", "settings.json"), "utf8")).hooks.PreToolUse;
  assert.equal(pre.filter((e) => JSON.stringify(e).includes("branch-guard.mjs")).length, 1);

  // malformed file -> not wired, reported, no throw
  const bad = tmpRepo();
  mkdirSync(join(bad, ".claude"), { recursive: true });
  writeFileSync(join(bad, ".claude", "settings.json"), "{ not json");
  const a3 = mergeSettings(bad);
  assert.equal(a3.wired, false);
});

test("mergeCodexHooks wires .codex/hooks.json, is idempotent, and survives malformed JSON", () => {
  const root = tmpRepo();
  const a1 = mergeCodexHooks(root);
  assert.equal(a1.wired, true);
  assert.equal(codexHookWiredIn(root), "hooks.json");
  const a2 = mergeCodexHooks(root);
  assert.equal(a2.wired, true);
  const pre = JSON.parse(readFileSync(join(root, ".codex", "hooks.json"), "utf8")).hooks.PreToolUse;
  assert.equal(pre.length, 1);
  assert.equal(pre[0].matcher, "Bash");
  // Command resolves the script from the git root (Codex runs hooks with the
  // session cwd, which may be a subdir), not a bare relative path.
  assert.match(pre[0].hooks[0].command, /git rev-parse --show-toplevel.*\.codex\/hooks\/branch-guard\.mjs/);

  const bad = tmpRepo();
  mkdirSync(join(bad, ".codex"), { recursive: true });
  writeFileSync(join(bad, ".codex", "hooks.json"), "nope");
  assert.equal(mergeCodexHooks(bad).wired, false);
});

test("orphanedHarnessArtifacts flags a dropped harness still on disk", () => {
  const root = tmpRepo();
  wireHooks(root, ["claude", "codex"]); // both hooks wired
  mkdirSync(join(root, ".agents", "skills", "create-issue"), { recursive: true });
  writeFileSync(join(root, ".agents", "skills", "create-issue", "SKILL.md"), "x");

  // narrowed to claude -> codex is now an orphan (wired hook + a file)
  const orphans = orphanedHarnessArtifacts(root, ["claude"]);
  assert.equal(orphans.length, 1);
  assert.equal(orphans[0].harness, "codex");
  assert.equal(orphans[0].wired, true);
  assert.ok(orphans[0].files.includes(".agents/skills/create-issue/SKILL.md"));

  // nothing orphaned when both are active
  assert.deepEqual(orphanedHarnessArtifacts(root, ["claude", "codex"]), []);
});

test("wireHooks wires exactly the active harnesses", () => {
  const both = tmpRepo();
  const rBoth = wireHooks(both, ["claude", "codex"]);
  assert.equal(rBoth.wired, true);
  assert.equal(rBoth.actions.length, 2);
  assert.equal(hookWiredIn(both), "settings.json");
  assert.equal(codexHookWiredIn(both), "hooks.json");

  const codexOnly = tmpRepo();
  const rCodex = wireHooks(codexOnly, ["codex"]);
  assert.equal(rCodex.actions.length, 1);
  assert.equal(hookWiredIn(codexOnly), null, "no Claude settings written for codex-only");
  assert.equal(codexHookWiredIn(codexOnly), "hooks.json");
});
