import { test, after } from "node:test";
import assert from "node:assert/strict";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { tmpRepo, cleanupAll, runCli } from "./helpers.mjs";

after(cleanupAll);

const readConfig = (root) => JSON.parse(readFileSync(join(root, "dienstweg.config.json"), "utf8"));
const has = (root, rel) => existsSync(join(root, rel));

const CLAUDE_FILES = [
  ".claude/commands/create-issue.md",
  ".claude/commands/start-task.md",
  ".claude/hooks/branch-guard.mjs",
  ".claude/settings.json",
];
const CODEX_FILES = [
  ".agents/skills/create-issue/SKILL.md",
  ".agents/skills/start-task/SKILL.md",
  ".codex/hooks/branch-guard.mjs",
  ".codex/hooks.json",
];

test("init --harness both writes both trees and check passes", () => {
  const root = tmpRepo();
  const init = runCli(["init", "--yes", "--harness", "both", "--name", "demo", "--prefix", "DEM"], root);
  assert.equal(init.status, 0, init.stderr);
  for (const f of [...CLAUDE_FILES, ...CODEX_FILES]) assert.ok(has(root, f), `missing ${f}`);
  assert.deepEqual(readConfig(root).harnesses, ["claude", "codex"]);
  assert.equal(runCli(["check"], root).status, 0);
});

test("init --harness claude writes only the Claude tree", () => {
  const root = tmpRepo();
  assert.equal(runCli(["init", "--yes", "--harness", "claude", "--name", "d", "--prefix", "D"], root).status, 0);
  for (const f of CLAUDE_FILES) assert.ok(has(root, f), `missing ${f}`);
  assert.ok(!has(root, ".codex"), ".codex must not exist");
  assert.ok(!has(root, ".agents"), ".agents must not exist");
  assert.equal(runCli(["check"], root).status, 0);
});

test("init --harness codex writes only the Codex tree", () => {
  const root = tmpRepo();
  assert.equal(runCli(["init", "--yes", "--harness", "codex", "--name", "d", "--prefix", "D"], root).status, 0);
  for (const f of CODEX_FILES) assert.ok(has(root, f), `missing ${f}`);
  assert.ok(!has(root, ".claude"), ".claude must not exist");
  assert.equal(runCli(["check"], root).status, 0);
});

test("update migrates a pre-v3 claude-only repo to both harnesses", () => {
  const root = tmpRepo();
  runCli(["init", "--yes", "--harness", "claude", "--name", "d", "--prefix", "D"], root);

  // Simulate a genuine pre-v3 config: no harnesses field, schema behind current.
  const cfg = readConfig(root);
  delete cfg.harnesses;
  cfg.schemaVersion = 2;
  writeFileSync(join(root, "dienstweg.config.json"), JSON.stringify(cfg, null, 2) + "\n");
  assert.ok(!has(root, ".codex"));

  const upd = runCli(["update"], root);
  assert.equal(upd.status, 0, upd.stderr);
  assert.match(upd.stdout, /migrated config to schema v3/);
  assert.deepEqual(readConfig(root).harnesses, ["claude", "codex"]);
  for (const f of CODEX_FILES) assert.ok(has(root, f), `update should add ${f}`);
  assert.equal(runCli(["check"], root).status, 0);
});

test("update --force is idempotent (no conflicts on a clean tree)", () => {
  const root = tmpRepo();
  runCli(["init", "--yes", "--harness", "both", "--name", "d", "--prefix", "D"], root);
  const u1 = runCli(["update", "--force"], root);
  assert.equal(u1.status, 0, u1.stderr);
  const u2 = runCli(["update", "--force"], root);
  assert.equal(u2.status, 0, u2.stderr);
  assert.doesNotMatch(u2.stdout, /CONFLICT/);
  assert.equal(runCli(["check"], root).status, 0);
});

test("recovery: a corrupt manifest is regenerated by update", () => {
  const root = tmpRepo();
  runCli(["init", "--yes", "--harness", "both", "--name", "d", "--prefix", "D"], root);
  writeFileSync(join(root, ".dienstweg", "manifest.json"), "{ corrupt");
  // check must diagnose, not crash.
  assert.equal(runCli(["check"], root).status, 1);
  const upd = runCli(["update"], root);
  assert.equal(upd.status, 0, upd.stderr);
  assert.equal(runCli(["check"], root).status, 0);
});

test("narrowing harnesses then update leaves orphans that check flags", () => {
  const root = tmpRepo();
  runCli(["init", "--yes", "--harness", "both", "--name", "d", "--prefix", "D"], root);
  // user narrows config.harnesses to claude only, then updates
  const cfg = readConfig(root);
  cfg.harnesses = ["claude"];
  writeFileSync(join(root, "dienstweg.config.json"), JSON.stringify(cfg, null, 2) + "\n");

  const upd = runCli(["update"], root);
  assert.equal(upd.status, 0, upd.stderr);
  assert.match(upd.stdout, /remain on disk/);
  assert.ok(has(root, ".codex/hooks.json"), "codex files are NOT auto-deleted");

  const chk = runCli(["check"], root);
  assert.equal(chk.status, 1);
  assert.match(chk.stderr, /harness 'codex' is not in config\.harnesses/);
});

test("check flags an unwired Codex hook", () => {
  const root = tmpRepo();
  runCli(["init", "--yes", "--harness", "both", "--name", "d", "--prefix", "D"], root);
  // Remove the branch-guard entry from .codex/hooks.json.
  writeFileSync(join(root, ".codex", "hooks.json"), JSON.stringify({ hooks: { PreToolUse: [] } }, null, 2));
  const chk = runCli(["check"], root);
  assert.equal(chk.status, 1);
  assert.match(chk.stderr, /not wired for Codex/);
});

// Environment doctor, end-to-end through the real CLI. Readings are injected via
// DIENSTWEG_ENV_DOCTOR (JSON) so the assertions never depend on the machine's real
// gh/claude/node - proving the runCheck merge, exit code, and FAIL/INFO wiring.
const initDemo = (root) =>
  assert.equal(runCli(["init", "--yes", "--harness", "both", "--name", "d", "--prefix", "D"], root).status, 0);

test("check surfaces environment-doctor FAILs (injected readings) and exits 1", () => {
  const root = tmpRepo();
  initDemo(root);
  const failing = JSON.stringify({
    node: { version: "18.0.0" },
    gh: { installed: true, authenticated: false },
    claudeCode: { installed: true, version: "2.1.100" },
    linearMcp: { visible: false },
  });
  const chk = runCli(["check"], root, { env: { DIENSTWEG_ENV_DOCTOR: failing } });
  assert.equal(chk.status, 1);
  assert.match(chk.stderr, />= 20/); // Node FAIL on stderr
  assert.match(chk.stderr, /not authenticated/); // gh FAIL on stderr
  assert.match(chk.stdout, /Linear MCP not detected/); // best-effort INFO on stdout
});

test("check passes with healthy injected environment readings", () => {
  const root = tmpRepo();
  initDemo(root);
  const healthy = JSON.stringify({
    node: { version: "22.0.0" },
    gh: { installed: true, authenticated: true },
    claudeCode: { installed: true, version: "9.9.9" },
    linearMcp: { visible: true },
  });
  const chk = runCli(["check"], root, { env: { DIENSTWEG_ENV_DOCTOR: healthy } });
  assert.equal(chk.status, 0, chk.stderr);
  assert.match(chk.stdout, /check: OK/);
});

test("check --json includes environment-doctor findings in problems/infos", () => {
  const root = tmpRepo();
  initDemo(root);
  const failing = JSON.stringify({
    node: { version: "18.0.0" },
    gh: { installed: false },
    claudeCode: { installed: true, version: "9.9.9" },
    linearMcp: { visible: false },
  });
  const chk = runCli(["check", "--json"], root, { env: { DIENSTWEG_ENV_DOCTOR: failing } });
  assert.equal(chk.status, 1);
  const parsed = JSON.parse(chk.stdout);
  assert.equal(parsed.ok, false);
  assert.ok(parsed.problems.some((p) => />= 20/.test(p)), "node FAIL should appear in json problems");
  assert.ok(parsed.infos.some((i) => /gh .*not found/i.test(i)), "gh INFO should appear in json infos");
});

test("check skips the environment doctor when the config is invalid JSON", () => {
  const root = tmpRepo();
  writeFileSync(join(root, "dienstweg.config.json"), "{ not valid json");
  const failing = JSON.stringify({
    node: { version: "18.0.0" },
    gh: { installed: false },
    claudeCode: { installed: true, version: "2.1.100" },
    linearMcp: { visible: false },
  });
  const chk = runCli(["check"], root, { env: { DIENSTWEG_ENV_DOCTOR: failing } });
  assert.equal(chk.status, 1);
  assert.match(chk.stderr, /not valid JSON/);
  // The doctor must NOT run without a loaded config: the config-error output stays
  // byte-for-byte as before, with none of the injected env findings leaking in.
  assert.doesNotMatch(chk.stdout + chk.stderr, />= 20/);
  assert.doesNotMatch(chk.stdout + chk.stderr, /Linear MCP not detected/);
});
