import {
  readFileSync,
  writeFileSync,
  existsSync,
  mkdirSync,
  chmodSync,
} from "node:fs";
import { createHash } from "node:crypto";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import {
  CLI_VERSION,
  STATE_DIR,
  MARKER_BEGIN,
  MARKER_END,
  manifestPath,
} from "./config.mjs";

const TEMPLATES_DIR = join(dirname(fileURLToPath(import.meta.url)), "..", "templates");

// Tool-owned files per harness. The branch-guard script is ONE shared template
// rendered byte-identically into each harness's hook dir (it self-adapts at
// runtime); the command surface differs by harness - Claude Code reads
// repo-committed slash-commands under .claude/commands, Codex reads
// repo-committed skills under .agents/skills (its non-deprecated, repo-shared
// prompt mechanism).
const HARNESS_FILES = {
  claude: [
    { template: "claude/commands/create-issue.md", target: ".claude/commands/create-issue.md", kind: "md" },
    { template: "claude/commands/start-task.md", target: ".claude/commands/start-task.md", kind: "md" },
    { template: "hooks/branch-guard.mjs", target: ".claude/hooks/branch-guard.mjs", kind: "mjs" },
  ],
  codex: [
    { template: "codex/skills/create-issue/SKILL.md", target: ".agents/skills/create-issue/SKILL.md", kind: "md" },
    { template: "codex/skills/start-task/SKILL.md", target: ".agents/skills/start-task/SKILL.md", kind: "md" },
    { template: "hooks/branch-guard.mjs", target: ".codex/hooks/branch-guard.mjs", kind: "mjs" },
  ],
};

// The tool-owned file specs for the given active harnesses, in a stable order.
// Every consumer that used to iterate a flat GENERATED_FILES list now derives
// the list from config.harnesses so inactive-harness files are never expected.
export function generatedFiles(harnesses) {
  const specs = [];
  for (const h of harnesses || []) {
    for (const spec of HARNESS_FILES[h] || []) specs.push(spec);
  }
  return specs;
}

export function sha256(content) {
  return createHash("sha256").update(content).digest("hex");
}

function generatedHeader(kind) {
  const text = `GENERATED by dienstweg v${CLI_VERSION} - DO NOT EDIT. Project values live in dienstweg.config.json, project-specific rules in dienstweg.local.md. Run \`dienstweg update\` to upgrade.`;
  return kind === "mjs" ? `// ${text}` : `<!-- ${text} -->`;
}

// Markdown commands start with YAML frontmatter; the header must go after it,
// otherwise the frontmatter is no longer the first thing in the file. Line
// endings are matched loosely so a CRLF checkout does not break detection.
export function renderGeneratedFile(templateRelPath, kind) {
  const raw = readFileSync(join(TEMPLATES_DIR, templateRelPath), "utf8");
  const header = generatedHeader(kind);
  if (kind === "md") {
    const fm = raw.match(/^---\r?\n[\s\S]*?\r?\n---\r?\n/);
    if (fm) return `${fm[0]}\n${header}\n${raw.slice(fm[0].length)}`;
  }
  if (kind === "mjs" && raw.startsWith("#!")) {
    const nl = raw.indexOf("\n");
    return `${raw.slice(0, nl + 1)}${header}\n${raw.slice(nl + 1)}`;
  }
  return `${header}\n\n${raw}`;
}

export function renderAgentsBlock(config) {
  const raw = readFileSync(join(TEMPLATES_DIR, "agents-block.md"), "utf8");
  const listOrDash = (arr) => (arr && arr.length ? arr.join(", ") : "-");
  const extraDoD = (config.extraDoD || []).map((line) => `- [ ] ${line}`).join("\n");
  const autoMerge = config.merge?.auto;
  if (typeof autoMerge !== "boolean") {
    throw new Error('cannot render AGENTS block: config value for "merge.auto" is missing or not a boolean. Run `dienstweg check`.');
  }
  // The two policies differ in behavior, not just wording, so the whole
  // paragraph is composed here instead of token-patched in the template.
  const mergeGates = `PR base = \`${config.git.baseBranch}\`, \`${config.gates.build}\` exit 0 after the last fix commits, no open DoD boxes (check via \`get_issue\` before merging), no open majority critical findings, re-review loop finished`;
  const mergePolicy = autoMerge
    ? `**Auto-merge (on, \`merge.auto: true\`):** after a clean review loop, merge autonomously - no asking. Gates (all mandatory): ${mergeGates}, no user override ("do not merge automatically" holds for the whole session). Gate violated -> do not merge, report status.`
    : `**Auto-merge (off, \`merge.auto: false\`):** NEVER merge autonomously. After a clean review loop: check off the DoD boxes, write \`## Final Summary\` (merge-SHA placeholder + PR number), set \`state="In Review"\`, then report the PR URL + gate status and stop - the merge is the user's decision. Merge only on an explicit user instruction; the gates (${mergeGates}) plus the post-merge base sync and the \`state="Done"\` close-out still apply then.`;
  const harnessLabel = (config.harnesses || [])
    .map((h) => (h === "claude" ? "Claude Code" : h === "codex" ? "Codex" : h))
    .join(" + ");
  const tokens = {
    version: CLI_VERSION,
    project: config.project,
    language: config.language,
    harnesses: harnessLabel,
    issuePrefix: config.tracker.issuePrefix,
    issuePrefixLower: config.tracker.issuePrefix.toLowerCase(),
    linearTeam: config.tracker.linearTeam,
    baseBranch: config.git.baseBranch,
    buildGates: config.gates.build,
    highRisk: listOrDash(config.areas.highRisk),
    singleWriter: listOrDash(config.areas.singleWriter),
    ensembleSize: String(config.review.ensembleSize),
    maxRounds: String(config.review.maxRounds),
    subagentType: config.review.subagentType,
    mergePolicy,
    extraDoD: extraDoD ? `\n${extraDoD}` : "",
    extraConstraints: listOrDash(config.extraConstraints),
  };
  let out = raw;
  for (const [key, value] of Object.entries(tokens)) {
    if (value === undefined || value === null) {
      throw new Error(`cannot render AGENTS block: config value for "${key}" is missing. Run \`dienstweg check\`.`);
    }
    out = out.replaceAll(`{{${key}}}`, String(value));
  }
  const leftover = out.match(/\{\{[a-zA-Z]+\}\}/);
  if (leftover) throw new Error(`unresolved token in agents-block template: ${leftover[0]}`);
  return `${MARKER_BEGIN}\n${out.trim()}\n${MARKER_END}`;
}

function writeFileEnsuringDir(path, content) {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content);
}

// Writes all tool-owned files for the active `harnesses` and returns the
// manifest object. `onConflict` decides what happens when a target exists with
// unexpected content: "overwrite" | "skip". Returns { manifest, skipped } where
// skipped lists targets left untouched.
export function writeGeneratedFiles(root, previousManifest, onConflict, harnesses) {
  const manifest = { dienstwegVersion: CLI_VERSION, files: {} };
  const skipped = [];
  for (const spec of generatedFiles(harnesses)) {
    const content = renderGeneratedFile(spec.template, spec.kind);
    const targetPath = join(root, spec.target);
    if (existsSync(targetPath)) {
      const currentHash = sha256(readFileSync(targetPath, "utf8"));
      const knownHash = previousManifest?.files?.[spec.target];
      const isNewContent = currentHash === sha256(content);
      if (!isNewContent && currentHash !== knownHash && onConflict === "skip") {
        skipped.push(spec.target);
        if (knownHash) manifest.files[spec.target] = knownHash;
        continue;
      }
    }
    writeFileEnsuringDir(targetPath, content);
    if (spec.kind === "mjs") chmodSync(targetPath, 0o755);
    manifest.files[spec.target] = sha256(content);
  }
  return { manifest, skipped };
}

export function writeManifest(root, manifest) {
  writeFileEnsuringDir(manifestPath(root), JSON.stringify(manifest, null, 2) + "\n");
}

// Reports the marker state of an AGENTS.md body: "clean" (exactly one well-
// ordered pair or none), or a description of the corruption. Shared by the
// generator (refuse to append into a corrupt file) and check.
export function agentsMarkerState(content) {
  const begins = (content.match(new RegExp(escapeRegExp(MARKER_BEGIN), "g")) || []).length;
  const ends = (content.match(new RegExp(escapeRegExp(MARKER_END), "g")) || []).length;
  if (begins === 0 && ends === 0) return { ok: true, present: false };
  if (begins === 1 && ends === 1) {
    if (content.indexOf(MARKER_END) < content.indexOf(MARKER_BEGIN)) {
      return { ok: false, reason: "dienstweg end marker appears before the begin marker" };
    }
    return { ok: true, present: true };
  }
  return { ok: false, reason: `expected one dienstweg marker pair, found ${begins} begin / ${ends} end markers` };
}

function escapeRegExp(s) {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

// Upserts the dienstweg block in AGENTS.md. Creates AGENTS.md if missing.
// Creates CLAUDE.md as an @AGENTS.md import only if CLAUDE.md does not exist.
// Throws on a corrupted marker state rather than duplicating or deleting content.
export function upsertAgentsBlock(root, block) {
  const agentsPath = join(root, "AGENTS.md");
  const claudePath = join(root, "CLAUDE.md");
  const actions = [];

  if (existsSync(agentsPath)) {
    const current = readFileSync(agentsPath, "utf8");
    const state = agentsMarkerState(current);
    if (!state.ok) {
      throw new Error(`AGENTS.md has corrupted dienstweg markers (${state.reason}). Fix or remove them, then re-run.`);
    }
    if (state.present) {
      const begin = current.indexOf(MARKER_BEGIN);
      const end = current.indexOf(MARKER_END);
      const updated = current.slice(0, begin) + block + current.slice(end + MARKER_END.length);
      writeFileSync(agentsPath, updated);
      actions.push("AGENTS.md: replaced dienstweg block");
    } else {
      writeFileSync(agentsPath, current.trimEnd() + "\n\n" + block + "\n");
      actions.push("AGENTS.md: appended dienstweg block");
    }
  } else {
    writeFileSync(agentsPath, `# AGENTS.md\n\n${block}\n`);
    actions.push("AGENTS.md: created with dienstweg block");
  }

  if (!existsSync(claudePath)) {
    writeFileSync(claudePath, "@AGENTS.md\n");
    actions.push("CLAUDE.md: created as @AGENTS.md import");
  } else {
    const claude = readFileSync(claudePath, "utf8");
    if (!claude.includes("@AGENTS.md")) {
      actions.push(
        "NOTE: existing CLAUDE.md does not import @AGENTS.md - wire this up manually or via the onboarding prompt",
      );
    }
  }
  return actions;
}

// Creates the project-owned local rules stub exactly once.
export function ensureLocalRules(root) {
  const p = join(root, "dienstweg.local.md");
  if (existsSync(p)) return false;
  const raw = readFileSync(join(TEMPLATES_DIR, "dienstweg.local.md"), "utf8");
  writeFileSync(p, raw);
  return true;
}

const HOOK_COMMAND = 'node "$CLAUDE_PROJECT_DIR/.claude/hooks/branch-guard.mjs"';

// True if the branch-guard is already wired in either settings file. Used so
// that wiring present in settings.local.json does not cause a duplicate append
// into settings.json.
export function hookWiredIn(root) {
  for (const name of ["settings.json", "settings.local.json"]) {
    const p = join(root, ".claude", name);
    if (!existsSync(p)) continue;
    try {
      const pre = JSON.parse(readFileSync(p, "utf8"))?.hooks?.PreToolUse;
      if (Array.isArray(pre) && pre.some((e) => (e?.hooks || []).some((h) => (h?.command || "").includes("branch-guard.mjs")))) {
        return name;
      }
    } catch {
      // A malformed file cannot wire the hook; check reports it separately.
    }
  }
  return null;
}

// Merges the branch-guard hook entry into .claude/settings.json without
// touching unrelated settings or existing hooks. Returns { wired, message }:
// `wired` is false when a malformed settings file prevented wiring, so callers
// can reflect that in their exit code instead of reporting a clean success.
export function mergeSettings(root) {
  const wiredIn = hookWiredIn(root);
  if (wiredIn) return { wired: true, message: `settings: branch-guard hook already wired (${wiredIn})` };

  const settingsPath = join(root, ".claude", "settings.json");
  let settings = {};
  if (existsSync(settingsPath)) {
    try {
      settings = JSON.parse(readFileSync(settingsPath, "utf8"));
    } catch {
      return { wired: false, message: "settings.json: NOT valid JSON - branch-guard hook was NOT wired; fix the file and re-run `dienstweg update`" };
    }
  }
  settings.hooks ??= {};
  settings.hooks.PreToolUse ??= [];
  if (!Array.isArray(settings.hooks.PreToolUse)) {
    return { wired: false, message: "settings.json: hooks.PreToolUse is not an array - branch-guard hook was NOT wired; fix the file and re-run `dienstweg update`" };
  }
  settings.hooks.PreToolUse.push({
    matcher: "Bash",
    hooks: [{ type: "command", command: HOOK_COMMAND }],
  });
  writeFileEnsuringDir(settingsPath, JSON.stringify(settings, null, 2) + "\n");
  return { wired: true, message: "settings.json: added branch-guard PreToolUse hook" };
}

// Codex discovers PreToolUse hooks in a repo-level .codex/hooks.json (same event
// schema Claude Code uses). The path is repo-root-relative because Codex exposes
// no project-dir env var; the script itself locates the config via the payload
// cwd + a parent-dir walk.
const CODEX_HOOK_COMMAND = "node .codex/hooks/branch-guard.mjs";

export function codexHookWiredIn(root) {
  const p = join(root, ".codex", "hooks.json");
  if (!existsSync(p)) return null;
  try {
    const pre = JSON.parse(readFileSync(p, "utf8"))?.hooks?.PreToolUse;
    if (Array.isArray(pre) && pre.some((e) => (e?.hooks || []).some((h) => (h?.command || "").includes("branch-guard.mjs")))) {
      return "hooks.json";
    }
  } catch {
    // A malformed file cannot wire the hook; check reports it separately.
  }
  return null;
}

// Merges the branch-guard entry into .codex/hooks.json without touching
// unrelated hooks. Mirrors mergeSettings: a malformed file yields wired:false so
// callers reflect it in their exit code instead of a false success.
export function mergeCodexHooks(root) {
  if (codexHookWiredIn(root)) {
    return { wired: true, message: "codex: branch-guard hook already wired (.codex/hooks.json)" };
  }
  const p = join(root, ".codex", "hooks.json");
  let hooks = {};
  if (existsSync(p)) {
    try {
      hooks = JSON.parse(readFileSync(p, "utf8"));
    } catch {
      return { wired: false, message: ".codex/hooks.json: NOT valid JSON - branch-guard hook was NOT wired; fix the file and re-run `dienstweg update`" };
    }
  }
  hooks.hooks ??= {};
  hooks.hooks.PreToolUse ??= [];
  if (!Array.isArray(hooks.hooks.PreToolUse)) {
    return { wired: false, message: ".codex/hooks.json: hooks.PreToolUse is not an array - branch-guard hook was NOT wired; fix the file and re-run `dienstweg update`" };
  }
  hooks.hooks.PreToolUse.push({
    matcher: "Bash",
    hooks: [{ type: "command", command: CODEX_HOOK_COMMAND }],
  });
  writeFileEnsuringDir(p, JSON.stringify(hooks, null, 2) + "\n");
  return { wired: true, message: ".codex/hooks.json: added branch-guard PreToolUse hook" };
}

// Wires the branch-guard for every active harness. Returns the per-harness
// results plus an overall `wired` flag (false if ANY active harness failed to
// wire) for the caller's warning + exit code.
export function wireHooks(root, harnesses) {
  const actions = [];
  if ((harnesses || []).includes("claude")) actions.push(mergeSettings(root));
  if ((harnesses || []).includes("codex")) actions.push(mergeCodexHooks(root));
  return { actions, wired: actions.every((a) => a.wired) };
}

export { STATE_DIR };
