import {
  readFileSync,
  writeFileSync,
  existsSync,
  mkdirSync,
  chmodSync,
} from "node:fs";
import { createHash } from "node:crypto";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import {
  CLI_VERSION,
  STATE_DIR,
  MARKER_BEGIN,
  MARKER_END,
  manifestPath,
} from "./config.mjs";

const TEMPLATES_DIR = join(dirname(fileURLToPath(import.meta.url)), "..", "templates");

export const GENERATED_FILES = [
  { template: "commands/create-issue.md", target: ".claude/commands/create-issue.md", kind: "md" },
  { template: "commands/start-task.md", target: ".claude/commands/start-task.md", kind: "md" },
  { template: "hooks/branch-guard.mjs", target: ".claude/hooks/branch-guard.mjs", kind: "mjs" },
];

export function sha256(content) {
  return createHash("sha256").update(content).digest("hex");
}

function generatedHeader(kind) {
  const text = `GENERATED by dienstweg v${CLI_VERSION} - DO NOT EDIT. Project values live in dienstweg.config.json, project-specific rules in dienstweg.local.md. Run \`dienstweg update\` to upgrade.`;
  return kind === "mjs" ? `// ${text}` : `<!-- ${text} -->`;
}

// Markdown commands start with YAML frontmatter; the header must go after it,
// otherwise the frontmatter is no longer the first thing in the file. Line
// endings are matched loosely so a CRLF checkout does not break detection.
export function renderGeneratedFile(templateRelPath, kind) {
  const raw = readFileSync(join(TEMPLATES_DIR, templateRelPath), "utf8");
  const header = generatedHeader(kind);
  if (kind === "md") {
    const fm = raw.match(/^---\r?\n[\s\S]*?\r?\n---\r?\n/);
    if (fm) return `${fm[0]}\n${header}\n${raw.slice(fm[0].length)}`;
  }
  if (kind === "mjs" && raw.startsWith("#!")) {
    const nl = raw.indexOf("\n");
    return `${raw.slice(0, nl + 1)}${header}\n${raw.slice(nl + 1)}`;
  }
  return `${header}\n\n${raw}`;
}

export function renderAgentsBlock(config) {
  const raw = readFileSync(join(TEMPLATES_DIR, "agents-block.md"), "utf8");
  const listOrDash = (arr) => (arr && arr.length ? arr.join(", ") : "-");
  const extraDoD = (config.extraDoD || []).map((line) => `- [ ] ${line}`).join("\n");
  const tokens = {
    version: CLI_VERSION,
    project: config.project,
    language: config.language,
    issuePrefix: config.tracker.issuePrefix,
    issuePrefixLower: config.tracker.issuePrefix.toLowerCase(),
    linearTeam: config.tracker.linearTeam,
    baseBranch: config.git.baseBranch,
    buildGates: config.gates.build,
    highRisk: listOrDash(config.areas.highRisk),
    singleWriter: listOrDash(config.areas.singleWriter),
    ensembleSize: String(config.review.ensembleSize),
    maxRounds: String(config.review.maxRounds),
    subagentType: config.review.subagentType,
    extraDoD: extraDoD ? `\n${extraDoD}` : "",
    extraConstraints: listOrDash(config.extraConstraints),
  };
  let out = raw;
  for (const [key, value] of Object.entries(tokens)) {
    if (value === undefined || value === null) {
      throw new Error(`cannot render AGENTS block: config value for "${key}" is missing. Run \`dienstweg check\`.`);
    }
    out = out.replaceAll(`{{${key}}}`, String(value));
  }
  const leftover = out.match(/\{\{[a-zA-Z]+\}\}/);
  if (leftover) throw new Error(`unresolved token in agents-block template: ${leftover[0]}`);
  return `${MARKER_BEGIN}\n${out.trim()}\n${MARKER_END}`;
}

function writeFileEnsuringDir(path, content) {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content);
}

// Writes all tool-owned files and returns the manifest object. `onConflict`
// decides what happens when a target exists with unexpected content:
// "overwrite" | "skip". Returns { manifest, skipped } where skipped lists
// targets left untouched.
export function writeGeneratedFiles(root, previousManifest, onConflict) {
  const manifest = { dienstwegVersion: CLI_VERSION, files: {} };
  const skipped = [];
  for (const spec of GENERATED_FILES) {
    const content = renderGeneratedFile(spec.template, spec.kind);
    const targetPath = join(root, spec.target);
    if (existsSync(targetPath)) {
      const currentHash = sha256(readFileSync(targetPath, "utf8"));
      const knownHash = previousManifest?.files?.[spec.target];
      const isNewContent = currentHash === sha256(content);
      if (!isNewContent && currentHash !== knownHash && onConflict === "skip") {
        skipped.push(spec.target);
        if (knownHash) manifest.files[spec.target] = knownHash;
        continue;
      }
    }
    writeFileEnsuringDir(targetPath, content);
    if (spec.kind === "mjs") chmodSync(targetPath, 0o755);
    manifest.files[spec.target] = sha256(content);
  }
  return { manifest, skipped };
}

export function writeManifest(root, manifest) {
  writeFileEnsuringDir(manifestPath(root), JSON.stringify(manifest, null, 2) + "\n");
}

// Reports the marker state of an AGENTS.md body: "clean" (exactly one well-
// ordered pair or none), or a description of the corruption. Shared by the
// generator (refuse to append into a corrupt file) and check.
export function agentsMarkerState(content) {
  const begins = (content.match(new RegExp(escapeRegExp(MARKER_BEGIN), "g")) || []).length;
  const ends = (content.match(new RegExp(escapeRegExp(MARKER_END), "g")) || []).length;
  if (begins === 0 && ends === 0) return { ok: true, present: false };
  if (begins === 1 && ends === 1) {
    if (content.indexOf(MARKER_END) < content.indexOf(MARKER_BEGIN)) {
      return { ok: false, reason: "dienstweg end marker appears before the begin marker" };
    }
    return { ok: true, present: true };
  }
  return { ok: false, reason: `expected one dienstweg marker pair, found ${begins} begin / ${ends} end markers` };
}

function escapeRegExp(s) {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

// Upserts the dienstweg block in AGENTS.md. Creates AGENTS.md if missing.
// Creates CLAUDE.md as an @AGENTS.md import only if CLAUDE.md does not exist.
// Throws on a corrupted marker state rather than duplicating or deleting content.
export function upsertAgentsBlock(root, block) {
  const agentsPath = join(root, "AGENTS.md");
  const claudePath = join(root, "CLAUDE.md");
  const actions = [];

  if (existsSync(agentsPath)) {
    const current = readFileSync(agentsPath, "utf8");
    const state = agentsMarkerState(current);
    if (!state.ok) {
      throw new Error(`AGENTS.md has corrupted dienstweg markers (${state.reason}). Fix or remove them, then re-run.`);
    }
    if (state.present) {
      const begin = current.indexOf(MARKER_BEGIN);
      const end = current.indexOf(MARKER_END);
      const updated = current.slice(0, begin) + block + current.slice(end + MARKER_END.length);
      writeFileSync(agentsPath, updated);
      actions.push("AGENTS.md: replaced dienstweg block");
    } else {
      writeFileSync(agentsPath, current.trimEnd() + "\n\n" + block + "\n");
      actions.push("AGENTS.md: appended dienstweg block");
    }
  } else {
    writeFileSync(agentsPath, `# AGENTS.md\n\n${block}\n`);
    actions.push("AGENTS.md: created with dienstweg block");
  }

  if (!existsSync(claudePath)) {
    writeFileSync(claudePath, "@AGENTS.md\n");
    actions.push("CLAUDE.md: created as @AGENTS.md import");
  } else {
    const claude = readFileSync(claudePath, "utf8");
    if (!claude.includes("@AGENTS.md")) {
      actions.push(
        "NOTE: existing CLAUDE.md does not import @AGENTS.md - wire this up manually or via the onboarding prompt",
      );
    }
  }
  return actions;
}

// Creates the project-owned local rules stub exactly once.
export function ensureLocalRules(root) {
  const p = join(root, "dienstweg.local.md");
  if (existsSync(p)) return false;
  const raw = readFileSync(join(TEMPLATES_DIR, "dienstweg.local.md"), "utf8");
  writeFileSync(p, raw);
  return true;
}

const HOOK_COMMAND = 'node "$CLAUDE_PROJECT_DIR/.claude/hooks/branch-guard.mjs"';

// Merges the branch-guard hook entry into .claude/settings.json without
// touching unrelated settings or existing hooks.
export function mergeSettings(root) {
  const settingsPath = join(root, ".claude", "settings.json");
  let settings = {};
  if (existsSync(settingsPath)) {
    try {
      settings = JSON.parse(readFileSync(settingsPath, "utf8"));
    } catch {
      return "settings.json: NOT valid JSON - branch-guard hook was NOT wired; fix the file and re-run `dienstweg update`";
    }
  }
  settings.hooks ??= {};
  settings.hooks.PreToolUse ??= [];
  if (!Array.isArray(settings.hooks.PreToolUse)) {
    return "settings.json: hooks.PreToolUse is not an array - branch-guard hook was NOT wired; fix the file and re-run `dienstweg update`";
  }
  const already = settings.hooks.PreToolUse.some((entry) =>
    (entry?.hooks || []).some((h) => (h?.command || "").includes("branch-guard.mjs")),
  );
  if (!already) {
    settings.hooks.PreToolUse.push({
      matcher: "Bash",
      hooks: [{ type: "command", command: HOOK_COMMAND }],
    });
    writeFileEnsuringDir(settingsPath, JSON.stringify(settings, null, 2) + "\n");
    return "settings.json: added branch-guard PreToolUse hook";
  }
  return "settings.json: branch-guard hook already wired";
}

export { STATE_DIR };
